<a href="https://colab.research.google.com/github/kahuroA/Descriptive-Statistics-Excercises/blob/main/Copy_of_Python_Programming_Simple_Random_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [1]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [2]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [20, 80, 100]
Choosing 3 random items from a list using sample function [40, 20, 20]


### <font color="green"> 1.0 Challenges</font>

In [3]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties=['Kiambu','Nairobi','Uasin Gishu', 'Mombasa', 'Nakuru','Machakos', 'Kitui', 'Muranga', 'Nyeri', 'Turkana']
random.sample(counties, k=2)

['Nyeri', 'Uasin Gishu']

## 2.0  Selecting the Random Sample from Dictionary

In [4]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Donald', 60), ('jhon', 70)]


### <font color="green">2.0 Challenges</font>

In [5]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#
package={'bronze package':{'starch':'rice', 'stew':'chicken curry', 'vegetable':'cabbages', 'desert':'melon'}, 'silver package':{'starch':'rice and chapati', 
                                                                                                                                 'stew':'beef curry', 'vegetable':'spinach', 'desert':'melon and bananas'},
         'gold package':{'starch':'rice, chappati and mukimo', 'stew':'beef curry', 'vegetable':'spinach and managu', 'desert':'tart'}}
random.sample(package.items(), k=2)

[('gold package',
  {'desert': 'tart',
   'starch': 'rice, chappati and mukimo',
   'stew': 'beef curry',
   'vegetable': 'spinach and managu'}),
 ('silver package',
  {'desert': 'melon and bananas',
   'starch': 'rice and chapati',
   'stew': 'beef curry',
   'vegetable': 'spinach'})]

## 3.0 Selecting a Random Sample with Replacement to including repetition


In [6]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Sarena', 'Mariya', 'Novac']


### <font color="green">3.0 Challenges</font>

In [7]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

random.choices(months, k=3)

['April', 'May', 'December']

## 4.0 Selecting a Random Sample from a Range of Integers

In [8]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [40, 75, 50, 55]


### <font color="green">4.1 Challenges</font>

In [9]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

random.sample(weight_set, k=4)

[4, 9, 7, 10]

## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [10]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[2 4 6]
[ 6 12 18]


### <font color="green">5.0 Challenges</font>

In [19]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  
randomRows = np.random.randint(6, size=2)
for i in randomRows:
  print(a[i])


[1, 2, 4, 5, 6]
[4, 8, 12, 16, 20]


In [16]:
randomRows.tolist()

[3, 1]

## 6.0 Selecting Random Samples from a Dataset

In [20]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
          PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
62811  9.598223e+12        5681834      F  ...       0            0       No
53332  9.839922e+13        5747970      F  ...       0            0       No
70272  4.765496e+12        5653822      F  ...       0            0       No
50983  6.529696e+12        5676634      F  ...       0            0       No
96374  6.193517e+13        5663484      M  ...       0            1       No
21531  4.694222e+13        5734718      F  ...       0          

### <font color="green">6.0 Challenges </font>

In [22]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
russian_df=pd.read_csv('http://bit.ly/DSRussianInvestigation')
russian_df.head(2)

investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon

[2 rows x 13 columns]

In [24]:
russian_df.sample(n=10, replace=False)

investigation investigation-start  ... american      president
83       iran-contra          1986-12-19  ...     True  Ronald Reagan
184           russia          2017-05-17  ...    False   Donald Trump
66         watergate          1973-05-19  ...     True  Richard Nixon
85       iran-contra          1986-12-19  ...     True  Ronald Reagan
17         watergate          1973-05-19  ...     True  Richard Nixon
72   hamilton-jordan          1979-11-29  ...     True   Jimmy Carter
9          watergate          1973-05-19  ...     True  Richard Nixon
181           russia          2017-05-17  ...    False   Donald Trump
160           russia          2017-05-17  ...     True   Donald Trump
157           herman          1998-05-26  ...    False   Bill Clinton

[10 rows x 13 columns]

In [25]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
df_med=pd.read_csv('http://bit.ly/MedicalAppointmentsDataset')
df_med.head()

PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]

In [26]:
df_med.sample(n=10, replace=False)

PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
16429   8.141980e+11        5636342      M  ...       0            0      Yes
41008   9.718652e+10        5740564      F  ...       0            0       No
105792  1.619288e+13        5722121      F  ...       0            1      Yes
26364   2.786646e+12        5707008      F  ...       0            0      Yes
54581   1.762886e+13        5672154      F  ...       0            0       No
25289   7.922588e+14        5619209      F  ...       0            0      Yes
103103  9.439625e+11        5748897      F  ...       0            0       No
81252   2.449457e+13        5656405      F  ...       0            0      Yes
7438    7.124589e+14        5740978      M  ...       0            0       No
37361   9.662187e+13        5636484      F  ...       0            0       No

[10 rows x 14 columns]